---
abstract: 'Simple logging interface with a contextual log'
author:
  - 'Arthur Axel "fREW" Schmidt <frioux+cpan@gmail.com>'
build_requires:
  Test::Fatal: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Contextual
requires:
  Carp: '0'
  Data::Dumper::Concise: '0'
  Exporter::Declare: '0.111'
  Moo: '1.003'
  Scalar::Util: '0'
version: '0.006004'
